stages:
  - test

rust-latest:
  stage: test
  image: rust:latest
  before_script:
    - apt-get install fuse
    - apt-get install libfuse-dev pkg-config
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  before_script:
    - apt-get install fuse
    - apt-get install libfuse-dev pkg-config
  script:
    - cargo build --verbose
    - cargo test --verbose
