stages:
  - test

rust-latest:
  stage: test
  image: rust:latest
  before_script:
    - apt update --yes --force-yes
    - apt install fuse --yes --force-yes
    - apt install libfuse-dev pkg-config --yes --force-yes
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  before_script:
    - apt update --yes --force-yes
    - apt install fuse --yes --force-yes
    - apt install libfuse-dev pkg-config --yes --force-yes
  script:
    - cargo build --verbose
    - cargo test --verbose
