[workspace]
members = ["gawires-gist"]

[package]
name = "gawires"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Roy"]
license = "GPLv3"
readme = "README.md"
repository = "https://github.com/metakernel/Gawires"
default-run = "gaw"

[[bin]]
name = "gaw"
path = "src/main.rs"

[lib]
name = "gawires"
path = "src/lib.rs"



[dependencies]
notify = "6.1.1"
libloading = "0.8.3"
clap = {version = "4.5.7", features = ["derive"]}
paw = "1.0.0"
interprocess = "2.2.0"
dirs = "5.0.1"
petgraph = "0.6.5"
blake2 = "0.10.6"
uuid = "1.8.0"

# Specific dependencies for the gawires kernel
gawires-diff = { git = "https://github.com/metakernel/gawires-diff"}
gawires-patch = { git = "https://github.com/metakernel/gawires-diff"}


[target.'cfg(unix)'.dependencies]
# Used for the filesystem in linux and macos
fuser = "0.14.0"

[target.'cfg(windows)'.dependencies]
# Used for the filesystem in windows
dokan = "0.3.1+dokan206"
windows = "0.57.0"

[target.'cfg(windows)'.build-dependencies]
windows = "0.57.0"
