[package]
name = "gawires-central"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gwcentral"
path = "src/main.rs"

[dependencies]
gawires-core = {path = "../core"}
gawires-gist = {path = "../gist"}